include ../Makefile.config

3_1 : 3_1.cpp 3_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 3_1.tsk 3_1.cpp 3_commons.cpp

3_2 : 3_2.cpp 3_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 3_2.tsk 3_2.cpp 3_commons.cpp
