include ../Makefile.config

17_1 : 17_1.cpp 17_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 17_1.tsk 17_1.cpp 17_commons.cpp

17_2 : 17_2.cpp 17_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 17_2.tsk 17_2.cpp 17_commons.cpp
