include ../Makefile.config

25_1 : 25_1.cpp 25_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 25_1.tsk 25_1.cpp 25_commons.cpp

25_2 : 25_2.cpp 25_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 25_2.tsk 25_2.cpp 25_commons.cpp
