include ../Makefile.config

20_1 : 20_1.cpp 20_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 20_1.tsk 20_1.cpp 20_commons.cpp

20_2 : 20_2.cpp 20_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 20_2.tsk 20_2.cpp 20_commons.cpp
