include ../Makefile.config

5_1 : 5_1.cpp 5_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 5_1.tsk 5_1.cpp 5_commons.cpp

5_2 : 5_2.cpp 5_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 5_2.tsk 5_2.cpp 5_commons.cpp
