include ../Makefile.config

24_1 : 24_1.cpp 24_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 24_1.tsk 24_1.cpp 24_commons.cpp

24_2 : 24_2.cpp 24_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 24_2.tsk 24_2.cpp 24_commons.cpp
