include ../Makefile.config

18_1 : 18_1.cpp 18_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 18_1.tsk 18_1.cpp 18_commons.cpp

18_2 : 18_2.cpp 18_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 18_2.tsk 18_2.cpp 18_commons.cpp
