include ../Makefile.config

12_1 : 12_1.cpp 12_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 12_1.tsk 12_1.cpp 12_commons.cpp

12_2 : 12_2.cpp 12_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 12_2.tsk 12_2.cpp 12_commons.cpp
