include ../Makefile.config

15_1 : 15_1.cpp 15_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 15_1.tsk 15_1.cpp 15_commons.cpp

15_2 : 15_2.cpp 15_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 15_2.tsk 15_2.cpp 15_commons.cpp
