include ../Makefile.config

14_1 : 14_1.cpp 14_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 14_1.tsk 14_1.cpp 14_commons.cpp

14_2 : 14_2.cpp 14_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 14_2.tsk 14_2.cpp 14_commons.cpp
