include ../Makefile.config

22_1 : 22_1.cpp 22_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 22_1.tsk 22_1.cpp 22_commons.cpp

22_2 : 22_2.cpp 22_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 22_2.tsk 22_2.cpp 22_commons.cpp
