include ../Makefile.config

23_1 : 23_1.cpp 23_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 23_1.tsk 23_1.cpp 23_commons.cpp

23_2 : 23_2.cpp 23_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 23_2.tsk 23_2.cpp 23_commons.cpp
