include ../Makefile.config

11_1 : 11_1.cpp 11_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 11_1.tsk 11_1.cpp 11_commons.cpp

11_2 : 11_2.cpp 11_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 11_2.tsk 11_2.cpp 11_commons.cpp
