include ../Makefile.config

16_1 : 16_1.cpp 16_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 16_1.tsk 16_1.cpp 16_commons.cpp

16_2 : 16_2.cpp 16_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 16_2.tsk 16_2.cpp 16_commons.cpp
