include ../Makefile.config

8_1 : 8_1.cpp 8_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 8_1.tsk 8_1.cpp 8_commons.cpp

8_2 : 8_2.cpp 8_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 8_2.tsk 8_2.cpp 8_commons.cpp
