include ../Makefile.config

10_1 : 10_1.cpp 10_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 10_1.tsk 10_1.cpp 10_commons.cpp

10_2 : 10_2.cpp 10_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 10_2.tsk 10_2.cpp 10_commons.cpp
