include ../Makefile.config

19_1 : 19_1.cpp 19_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 19_1.tsk 19_1.cpp 19_commons.cpp

19_2 : 19_2.cpp 19_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 19_2.tsk 19_2.cpp 19_commons.cpp
