include ../Makefile.config

2_1: 2_1.cpp 2_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 2_1.tsk 2_1.cpp 2_commons.cpp

2_2: 2_2.cpp 2_commons.cpp
	${COMPILER} ${COMPILER_OPTS}-o 2_2.tsk 2_2.cpp 2_commons.cpp
