include ../Makefile.config

9_1 : 9_1.cpp 9_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 9_1.tsk 9_1.cpp 9_commons.cpp

9_2 : 9_2.cpp 9_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 9_2.tsk 9_2.cpp 9_commons.cpp
