include ../Makefile.config

6_1 : 6_1.cpp 6_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 6_1.tsk 6_1.cpp 6_commons.cpp

6_2 : 6_2.cpp 6_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 6_2.tsk 6_2.cpp 6_commons.cpp
