include ../Makefile.config

4_1 : 4_1.cpp 4_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 4_1.tsk 4_1.cpp 4_commons.cpp

4_2 : 4_2.cpp 4_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 4_2.tsk 4_2.cpp 4_commons.cpp
