include ../Makefile.config

13_1 : 13_1.cpp 13_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 13_1.tsk 13_1.cpp 13_commons.cpp

13_2 : 13_2.cpp 13_commons.cpp
	${COMPILER} ${COMPILER_OPTS} -o 13_2.tsk 13_2.cpp 13_commons.cpp
